In [1]:
#Auotograd
import torch

In [2]:
x=torch.ones(2,2,requires_grad=True)
print(x)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
y=x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
#y是一次运算的结果，所以是有grad_fn的
print(y.grad_fn)

In [5]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [6]:
a=torch.rand(2,2)
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)


False
True


In [7]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
x=torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y=y*2
print(y)

tensor([ 1503.1361,  -423.3788, -1084.8182], grad_fn=<MulBackward0>)


In [10]:
v=torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [ ]:
#define the network
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net,self).__init__()
        #一个输入通道，6个输出通道，3x3卷积核
        #kernel1
        self.conv1=nn.Conv2d(1,6,3)#对应的是输入，输出通道，核大小
        self.conv2=nn.Conv2d(6,16,3)
        #affine计算
        self.fc1=nn.Linear(16*6*6,120)
        self.fc2=nn.Linear(120,84)