In [1]:
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39],
        [9.7346e-39, 1.0745e-38, 1.0102e-38]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.5136, 0.3728, 0.0700],
        [0.9629, 0.9671, 0.9213],
        [0.7046, 0.6868, 0.1409],
        [0.3271, 0.9426, 0.4022],
        [0.9171, 0.9477, 0.8985]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5580,  0.4026,  1.5441],
        [ 1.1689, -0.1344,  0.1588],
        [-0.1300, -1.2169, -0.2444],
        [-1.6961, -1.3372,  0.7064],
        [ 0.2113, -0.4972,  0.0542]])


In [7]:
print(x.size())
print(x.shape)#返回值是tuple支持tuple的所有操作

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])


In [10]:
print(torch.add(x,y))
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])
tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])


In [11]:
y.add_(x)#所有inplace版本都有后缀

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])

In [12]:
#索引，类似numpy的索引操作来访问，索引出来的结果是和原数据共享内存的
y=x[0,:]
y+=1
print(y)
print(x[0,:])

tensor([2.5580, 1.4026, 2.5441])
tensor([2.5580, 1.4026, 2.5441])


In [14]:
#用view来改变tensor的形状，但是是共享data的
y=x.view(15)
print(y)
#要获得真的副本，需要用reshape()改变形状,但是不能保证返回拷贝，所以推荐用clone创建一个副本再用view()
x_cp=x.clone().view(15)
print(x_cp)
#而且使用clone会被记录在计算图中

tensor([ 2.5580,  1.4026,  2.5441,  1.1689, -0.1344,  0.1588, -0.1300, -1.2169,
        -0.2444, -1.6961, -1.3372,  0.7064,  0.2113, -0.4972,  0.0542])
tensor([ 2.5580,  1.4026,  2.5441,  1.1689, -0.1344,  0.1588, -0.1300, -1.2169,
        -0.2444, -1.6961, -1.3372,  0.7064,  0.2113, -0.4972,  0.0542])


In [15]:
#item()把标量转化成python number
x=torch.randn(1)
print(x)
print(x.item())


tensor([-1.8057])
-1.8056740760803223
