In [1]:
import torch

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39],
        [1.0378e-38, 9.6429e-39, 9.2755e-39],
        [9.7346e-39, 1.0745e-38, 1.0102e-38]])


In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.5136, 0.3728, 0.0700],
        [0.9629, 0.9671, 0.9213],
        [0.7046, 0.6868, 0.1409],
        [0.3271, 0.9426, 0.4022],
        [0.9171, 0.9477, 0.8985]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x=x.new_ones(5,3,dtype=torch.float64)
print(x)
x=torch.randn_like(x,dtype=torch.float)
print(x)


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.5580,  0.4026,  1.5441],
        [ 1.1689, -0.1344,  0.1588],
        [-0.1300, -1.2169, -0.2444],
        [-1.6961, -1.3372,  0.7064],
        [ 0.2113, -0.4972,  0.0542]])


In [7]:
print(x.size())
print(x.shape)#返回值是tuple支持tuple的所有操作

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y=torch.rand(5,3)
print(x+y)

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])


In [10]:
print(torch.add(x,y))
result=torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])
tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])


In [11]:
y.add_(x)#所有inplace版本都有后缀

tensor([[ 2.3735,  0.6952,  1.6369],
        [ 2.0509,  0.4700,  0.1632],
        [ 0.3748, -0.2851, -0.1982],
        [-0.9946, -1.3075,  1.1628],
        [ 0.9147,  0.3067,  0.5907]])

In [12]:
#索引，类似numpy的索引操作来访问，索引出来的结果是和原数据共享内存的
y=x[0,:]
y+=1
print(y)
print(x[0,:])

tensor([2.5580, 1.4026, 2.5441])
tensor([2.5580, 1.4026, 2.5441])


In [14]:
#用view来改变tensor的形状，但是是共享data的
y=x.view(15)
print(y)
#要获得真的副本，需要用reshape()改变形状,但是不能保证返回拷贝，所以推荐用clone创建一个副本再用view()
x_cp=x.clone().view(15)
print(x_cp)
#而且使用clone会被记录在计算图中

tensor([ 2.5580,  1.4026,  2.5441,  1.1689, -0.1344,  0.1588, -0.1300, -1.2169,
        -0.2444, -1.6961, -1.3372,  0.7064,  0.2113, -0.4972,  0.0542])
tensor([ 2.5580,  1.4026,  2.5441,  1.1689, -0.1344,  0.1588, -0.1300, -1.2169,
        -0.2444, -1.6961, -1.3372,  0.7064,  0.2113, -0.4972,  0.0542])


In [15]:
#item()把标量转化成python number
x=torch.randn(1)
print(x)
print(x.item())


tensor([-1.8057])
-1.8056740760803223


In [2]:
#内存开销：索引操作不会开辟新内存，但是y=x+y会开新内存，然后y指向新的内存。python自带的id函数表示内存地址，用此实验
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y=y+x
print(id(y)==id_before)`

False


In [3]:
#如果要把结果放在原来y的内存，则用索引进行操作
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)
y[:]=y+x
print(id(y)==id_before)

#虽然view返回的Tensor与原来的是共享data的，但是依然是一个新的Tensor,有不同的id,因为除了data外，tensor还包含其他的信息

True


In [4]:
#tensor和Numpy相互转换，注意转换后是公用内存的。但是用torch.tensor()方法就会拷贝
a=torch.ones(5)
b=a.numpy()
print(a,b)

a+=1
print(a,b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [5]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a,b)

a+=1
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [6]:
c=torch.tensor(a)
a+=1
print(a,c)

[3. 3. 3. 3. 3.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [7]:
#tensor on GPU
if torch.cuda.is_available():
    device=torch.device("cuda")
    y=torch.ones_like(x,device=device)
    x=x.to(device)
    z=x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([2, 3], device='cuda:0')
tensor([2., 3.], dtype=torch.float64)


自动求梯度

In [8]:
#Tensor是这个包的核心类，把.requires_grad设为true,就会开始追踪所有操作，完成计算后调用backward()就可以完成所有梯度计算，梯度累积到.grad属性中
#不想被继续追踪就调用detach().或使用with torch.no_grad()
#Function是一个很重要的类，与Tensor结合就能构建一个记录整个计算过程的有向无环图，每个Tensor都有.grad_fn属性，该属性是创建该Tensor的Function
x=torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [9]:
y=x+2
print(y)
print(y.grad_fn)
#x是直接创建的，没有梯度，称为叶子节点，而y是通过加法创建的，有一个为AddBackward的梯度

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
print(x.is_leaf,y.is_leaf)

True False


In [11]:
z=y*y*3
out=z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [12]:
a=torch.randn(2,2)#缺失情况下，默认requires_grad=False
a=((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b=(a*a).sum()
print(b.grad_fn)

False
True


In [13]:
#由于outr是一个标量，所以调用backward()时不需要指定求导变量
out.backward()

In [14]:
print(x.grad)#这是out关于x的梯度

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
out2=x.sum()
out2.backward()
print(x.grad)

out3=x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)


tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [17]:
x=torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)
y=2*x
z=y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [18]:
v=torch.tensor([[1.0,0.1],[0.01,0.001]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [19]:
#中断梯度追踪
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2 
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad) # True
print(y2, y2.requires_grad) # False
print(y3, y3.requires_grad) # True


True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [20]:
y3.backward()
print(x.grad)
#y2的梯度是不能回传的，y2也不能调用backward()

tensor(2.)


In [21]:
#想更改tensor的数值又不被autograd记录，可以对tensor.data进行操作
x = torch.ones(1,requires_grad=True)

print(x.data) # 还是一个tensor
print(x.data.requires_grad) # 但是已经是独立于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x) # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
